import type { Metadata } from 'next';
import '@/styles/index.css';
import { ThemeProvider } from '@/providers/ThemeProvider';
import { TrpcProvider } from '@/providers/TrpcProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <TrpcProvider>
          <ThemeProvider>{children}</ThemeProvider>
        </TrpcProvider>
      </body>
    </html>
  );
}
